### PR TITLE
Translator tool

### PR DESCRIPTION
**Pull request by Johann150**
The translating tool is now basically working.
Without jQuery 😉

But there are still things that might have to be fixed e.g. adding new keys/languages or removing keys/languages. Also checking on user input (it should not be empty) would be good.

### CODE REVIEW

**Comment by jugendhacker** [comment]
Why do you made this? My work is now useless! And why without jQuery?

**Comment by jugendhacker** [comment]
And I would clean up the code when I would be finished!

**Comment by Johann150** [comment]
I did not intend that, but I saw that there were no commits so I thought I might as well do something.

**Comment by jugendhacker** [comment]
OK let's make it like this: we close your pull request and use my code for the frontend and you can write the backend in the back.php to save all the stuff, okay?

**Comment by Johann150** [comment]
Thats where it gets complicated because we would have to **agree on an interface/API** to use. But that would be okay with me.

**Comment by jugendhacker** [comment]
OK! In the moment I just fetch the table and send it as a Ajax/JSON Post to the backend!

**Pull request closed without merging**
